import crypto from "node:crypto"; import type {NextFunction,Request,Response} from "express"; import {ADMIN_TOKEN} from "../constants.js"; import {dbGet,dbRun} from "../storage/db.js"; import {touchUser} from "../storage/users.js";
export const LOCAL_USER_ID="local"; export function scopedKey(userId:string,base:string){return userId===LOCAL_USER_ID?base:`${userId}:${base}`;}
const TTL=30*24*60*60*1000; const hash=(t:string)=>crypto.createHash("sha256").update(t).digest("hex");
export async function createSession(userId:string){const token=crypto.randomBytes(32).toString("base64url");await dbRun("INSERT INTO sessions (token_hash,user_id,expires_at) VALUES (?,?,?)",[hash(token),userId,Date.now()+TTL]);return token;}
export async function resolveSession(token:string){const r=await dbGet<{user_id:string;expires_at:number|string}>("SELECT user_id,expires_at FROM sessions WHERE token_hash=?",[hash(token)]);if(!r)return null;if(Date.now()>Number(r.expires_at)){await destroySession(token);return null;}return r.user_id;}
export async function destroySession(token:string){await dbRun("DELETE FROM sessions WHERE token_hash=?",[hash(token)]);} export async function destroyUserSessions(id:string){await dbRun("DELETE FROM sessions WHERE user_id=?",[id]);}
function bearer(req:Request){const h=req.headers.authorization;const m=/^Bearer\s+(.+)$/i.exec(String(h||""));return m?m[1].trim():null;}
declare global{namespace Express{interface Request{userId?:string}}}
const seen=new Map<string,number>(); async function touch(id:string){const now=Date.now();if(now-(seen.get(id)||0)<300000)return;seen.set(id,now);try{await touchUser(id,now);}catch{}}
export async function requireAuth(req:Request,res:Response,next:NextFunction){const t=bearer(req);if(!t)return void res.status(401).json({ok:false,error:"unauthorized"});const id=await resolveSession(t);if(!id)return void res.status(401).json({ok:false,error:"unauthorized"});req.userId=id;void touch(id);next();}
export function requireAdmin(req:Request,res:Response,next:NextFunction){if(!ADMIN_TOKEN)return void res.status(401).json({ok:false,error:"admin_disabled"});const a=Buffer.from(bearer(req)||""),b=Buffer.from(ADMIN_TOKEN);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return void res.status(401).json({ok:false,error:"unauthorized"});next();}
