import crypto from "node:crypto"; import { dbGet,dbQuery,dbRun } from "./db.js";
export type Invite={code:string;createdAt:number;usedBy:string|null;usedAt:number|null;note:string|null}; type R={code:string;created_at:number|string;used_by:string|null;used_at:number|string|null;note:string|null};
const A="ABCDEFGHJKMNPQRSTUVWXYZ23456789"; function gen(n=10){const b=crypto.randomBytes(n);return [...b].map(x=>A[x%A.length]).join("");} function row(r:R):Invite{return{code:r.code,createdAt:Number(r.created_at),usedBy:r.used_by,usedAt:r.used_at==null?null:Number(r.used_at),note:r.note};}
export async function createInvites(count:number,note?:string){const out:Invite[]=[];for(let i=0;i<Math.max(1,Math.min(100,Math.floor(count)||1));i++){let code=gen();for(let t=0;t<5;t++){try{await dbRun("INSERT INTO invites (code,created_at,used_by,used_at,note) VALUES (?,?,NULL,NULL,?)",[code,Date.now(),note??null]);break;}catch{code=gen();}}out.push({code,createdAt:Date.now(),usedBy:null,usedAt:null,note:note??null});}return out;}
export async function listInvites(){return (await dbQuery<R>("SELECT * FROM invites ORDER BY created_at DESC")).map(row);}
export async function consumeInvite(code:string,userId:string){return await dbRun("UPDATE invites SET used_by=?,used_at=? WHERE code=? AND used_by IS NULL",[userId,Date.now(),code])===1;}
export async function isInviteUsable(code:string){const r=await dbGet<{used_by:string|null}>("SELECT used_by FROM invites WHERE code=?",[code]);return !!r&&r.used_by===null;}
export async function revokeInvite(code:string){return await dbRun("DELETE FROM invites WHERE code=? AND used_by IS NULL",[code])===1;}
export async function inviteStats(){const [t,u]=await Promise.all([dbGet<{n:number|string}>("SELECT COUNT(*) AS n FROM invites"),dbGet<{n:number|string}>("SELECT COUNT(*) AS n FROM invites WHERE used_by IS NOT NULL")]);const total=Number(t?.n||0),used=Number(u?.n||0);return{total,used,unused:total-used};}
